### ISSUE TITLE
minor error in  train_esrgan.py and train_psnr_rrdb.py

### ISSUE THREAD

**Issue by seragENTp** [sony/nnabla-examples#127]
avg_psnr = avg_psnr / idx
should be :
avg_psnr = avg_psnr / val_samples

**Comment by TE-andrewshin** [comment]
Thanks for pointing out! We will fix the bug accordingly.

**Comment by TE-andrewshin** [comment]
This has been resolved by https://github.com/sony/nnabla-examples/pull/131
