### ISSUE TITLE
ONNX Operators Implementation

### ISSUE THREAD

**Issue by jay-karan** [sony/nnabla-examples#179]
- Please redirect me to the kernel level code (Implementation) of ONNX Operators by nnabla.
- Please help me in understanding at nnabla from developer perspective.

**Comment by TomonobuTsujikawa** [comment]
Sorry late response.
The code involved onnx operators in placed in:
https://github.com/sony/nnabla/tree/master/python/src/nnabla/utils/converter/onnx

exporter.py: implements a mapping from nnabla to onnx operators.
importer.py: implements a mapping from onnx to nnabla operators.
utils.py some misc helper functions.

**Comment by TomonobuTsujikawa** [comment]
I hope you are satisfied with this answer.
Please create new github issue if you have questions.
