### ISSUE TITLE
Pretrained Weights links failed

### ISSUE THREAD

**Issue by aidlearning** [sony/nnabla-examples#192]
Pretrained Weights of first-order-model  links failed! pls check it

**Comment by TomonobuTsujikawa** [comment]
Hi,  thank you for your information.
I think you pointed pretrained weight section in [this README file](https://github.com/sony/nnabla-examples/blob/master/GANs/first-order-model/README.md), right?

I checked the link just now, and there is no problem, so I hope you can download h5 file from https://nnabla.org/pretrained-models/nnabla-examples/GANs/first-order-model/pretrained_fomm_params.h5 .
Could you please check it again?

Please let me know if my pointing link is wrong.

**Comment by aidlearning** [comment]
Yes, it's working now ,thanks a lot!
