### ISSUE TITLE
FlowNet

### ISSUE THREAD

**Issue by Armin234** [sony/nnabla-examples#344]
Hello,
is there an example of FlowNet (Correlation) implementation with nnabla ? Or another simple example for optical flow estimation ?

Regards 
Armin

**Comment by TakuyaNarihira** [comment]
Thanks for the query! We have an instance of flow estimator network architecture implementation in our video super-resolution example (TecoGAN).
https://github.com/sony/nnabla-examples/blob/master/video-superresolution/tecogan/models.py#L39

```python
# Example usage
frames = F.concatenate(previous_frame, current_frame)  # (N, H, W, C * 2)
flow = flow_estimator(frames)  # (N, H, W, 2)  2 is (dx, dy)
```

(Note that the channel dimension comes last in this implementation.)

You may get the pre-trained flow estimator from the pretrained tecogan model, or by training the model from scratch using opticalflow dataset.

Sorry that unfortunately we don't have flownet implementation in our repository.

**Comment by Armin234** [comment]
thank you, this should help me a lot
