### ISSUE TITLE
I would like to ask why my reasoning results are all black graphs?

### ISSUE THREAD

**Issue by 123456klk1** [sony/nnabla-examples#368]
![image](https://user-images.githubusercontent.com/53042912/219990783-33f59782-fce0-42d4-b651-5b6247a316c8.png)
python generate.py generate.config=F:\herong\diffusion-models\config_cifar10_32x32.yaml generate.h5=F:\herong\diffusion-models\params_cifar.h5
Hi, thank you very much for your work, I would like to ask why my reasoning results are all black graphs?

**Comment by AkioHayakawa** [comment]
Hi, thanks for your question.
Actually, this is a bug and we believe we fix this in this [PR](#370).

Could you try it again with the current master? 
If you still have black images, please let us know.

**Comment by 123456klk1** [comment]
Thank you so much for your reply, I can't wait to try it out!

**Comment by 123456klk1** [comment]
Thank you very much, I can play your project normally now!
