### ISSUE TITLE
Runtime errors in colab Stylegan2 

### ISSUE THREAD

**Issue by wennycooper** [sony/nnabla-examples#379]
I tried to run the colab of stylegan2 in https://colab.research.google.com/github/sony/nnabla-examples/blob/master/interactive-demos/stylegan2.ipynb
But I got runtime error in nn.load_parameters("styleGAN2_G_params.h5")

![螢幕擷取畫面 2023-05-06 145109](https://user-images.githubusercontent.com/7479445/236608313-d3d20bba-a3f9-4563-9d01-7f9c809d0253.png)

Is there any solution?

**Comment by TomonobuTsujikawa** [comment]
Sorry for taking some time.

I reproduced your issue, and I found Colab environment has old Pillow.
So, could you please try this command?
```bash
!pip install -U Pillow
```
This will show the warning message, so you need to push `RESTART RUNTIME` button.

This Restarting will reset your current directory, so you need to execute following command again:
```bash
%cd nnabla-examples/image-generation/stylegan2
```

We will update Colab instruction or requirements for nnabla.
I hope this instruction will help you.

**Comment by wennycooper** [comment]
Yes, it works. Thank you!
